version: "3.9"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - ./data/:/data
    environment:
      EULA: TRUE
      TYPE: SPIGOT
      OPS: jroc83
      SPIGET_RESOURCES: 1331
